//! Generated by tools/gen_probes.py -- do not edit by hand.
//!
//! Every zero-argument `const` member of the listed classes returning a
//! bool or an enum. They take no arguments to get wrong and cannot mutate
//! game state, which makes them safe to call speculatively from the frame
//! hook while a human opens and closes UI panels.
//!
//! Caveat: a `virtual` getter is called here through its base-class
//! implementation, bypassing dispatch. Fine for discovery, not for use.

use super::probe::{Kind, Probe};

/// Called with `this` = GameEngine*.
pub const PROBES_ENGINE: &[Probe] = &[
    // bool
    Probe { label: "GameEngine::AllowRagdolls", symbol: "?AllowRagdolls@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetAutoSave", symbol: "?GetAutoSave@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetCloudStorage", symbol: "?GetCloudStorage@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugAttachpoints", symbol: "?GetDebugAttachpoints@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugDestructibles", symbol: "?GetDebugDestructibles@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugItems", symbol: "?GetDebugItems@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugMonsters", symbol: "?GetDebugMonsters@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugProjectiles", symbol: "?GetDebugProjectiles@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugProxies", symbol: "?GetDebugProxies@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugQuestTokens", symbol: "?GetDebugQuestTokens@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugSetpieces", symbol: "?GetDebugSetpieces@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetDebugTransparency", symbol: "?GetDebugTransparency@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // enum GameDifficulty
    Probe { label: "GameEngine::GetGameDifficulty", symbol: "?GetGameDifficulty@GameEngine@GAME@@QEBA?AW4GameDifficulty@2@XZ", kind: Kind::Enum },
    // enum GameMode
    Probe { label: "GameEngine::GetGameMode", symbol: "?GetGameMode@GameEngine@GAME@@QEBA?AW4GameMode@2@XZ", kind: Kind::Enum },
    // enum InputMode
    Probe { label: "GameEngine::GetInputMode", symbol: "?GetInputMode@GameEngine@GAME@@QEBA?AW4InputMode@2@XZ", kind: Kind::Enum },
    // enum LootMode
    Probe { label: "GameEngine::GetLootMode", symbol: "?GetLootMode@GameEngine@GAME@@QEBA?AW4LootMode@2@XZ", kind: Kind::Enum },
    // enum ZonePage
    Probe { label: "GameEngine::GetMainPlayersPersonalPortalZone", symbol: "?GetMainPlayersPersonalPortalZone@GameEngine@GAME@@QEBA?AW4ZonePage@2@XZ", kind: Kind::Enum },
    // bool
    Probe { label: "GameEngine::GetMinDamageDebugging", symbol: "?GetMinDamageDebugging@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetPlayerCompletedLevel", symbol: "?GetPlayerCompletedLevel@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetPlayerRespawn", symbol: "?GetPlayerRespawn@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetPlayerUnlockedLevel", symbol: "?GetPlayerUnlockedLevel@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::GetShowInstancedItems", symbol: "?GetShowInstancedItems@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsDungeonBonusComplete", symbol: "?IsDungeonBonusComplete@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsDungeonBossDead", symbol: "?IsDungeonBossDead@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsGameEngineOnline", symbol: "?IsGameEngineOnline@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsGameLoading", symbol: "?IsGameLoading@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsLeftTriggerDown", symbol: "?IsLeftTriggerDown@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsMouseLocked", symbol: "?IsMouseLocked@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsNewTransmuteFile", symbol: "?IsNewTransmuteFile@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsNpcTalkingAllowed", symbol: "?IsNpcTalkingAllowed@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsRenderingEnabled", symbol: "?IsRenderingEnabled@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsRightTriggerDown", symbol: "?IsRightTriggerDown@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsSaveEnabled", symbol: "?IsSaveEnabled@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsServerOrSingle", symbol: "?IsServerOrSingle@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsTransferOpen", symbol: "?IsTransferOpen@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsUltimateVeteran", symbol: "?IsUltimateVeteran@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::IsViewDistanceLocked", symbol: "?IsViewDistanceLocked@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::MainPlayerCanUseAscendantAltar", symbol: "?MainPlayerCanUseAscendantAltar@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::MainPlayerCanUseConvert", symbol: "?MainPlayerCanUseConvert@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::MainPlayerCanUseDismantle", symbol: "?MainPlayerCanUseDismantle@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::MainPlayerCanUsePersonalTeleport", symbol: "?MainPlayerCanUsePersonalTeleport@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::MainPlayerCanUseReroll", symbol: "?MainPlayerCanUseReroll@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::MainPlayerHasPersonalTeleport", symbol: "?MainPlayerHasPersonalTeleport@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::NeedsSleep", symbol: "?NeedsSleep@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "GameEngine::UIExists", symbol: "?UIExists@GameEngine@GAME@@QEBA_NXZ", kind: Kind::Bool },
];

/// Called with `this` = Player* (usable as Character*).
pub const PROBES_CHARACTER: &[Probe] = &[
    // bool
    Probe { label: "Character::AllocateAllAnimSets", symbol: "?AllocateAllAnimSets@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::AlwaysWarps", symbol: "?AlwaysWarps@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::AreMessagesVisible", symbol: "?AreMessagesVisible@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::CanInterruptMovement", symbol: "?CanInterruptMovement@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::CanWalk", symbol: "?CanWalk@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::CausesAnger", symbol: "?CausesAnger@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::CheckForcedUpdateLoadSphere", symbol: "?CheckForcedUpdateLoadSphere@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::DeathCanFinish", symbol: "?DeathCanFinish@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::DeleteOnEnteringUnloadedLevel", symbol: "?DeleteOnEnteringUnloadedLevel@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::DisallowsMovement", symbol: "?DisallowsMovement@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::DoDebugRender", symbol: "?DoDebugRender@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // enum Character_ActionState const
    Probe { label: "Character::GetActionState", symbol: "?GetActionState@Character@GAME@@UEBA?BW4Character_ActionState@2@XZ", kind: Kind::Enum },
    // bool
    Probe { label: "Character::GetAllowedOffNavmesh", symbol: "?GetAllowedOffNavmesh@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::GetDismissBehavior", symbol: "?GetDismissBehavior@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // enum FactionType
    Probe { label: "Character::GetFaction", symbol: "?GetFaction@Character@GAME@@QEBA?AW4FactionType@2@XZ", kind: Kind::Enum },
    // enum Character_Gender
    Probe { label: "Character::GetGender", symbol: "?GetGender@Character@GAME@@UEBA?AW4Character_Gender@2@XZ", kind: Kind::Enum },
    // enum Character_LifeState const
    Probe { label: "Character::GetLifeState", symbol: "?GetLifeState@Character@GAME@@UEBA?BW4Character_LifeState@2@XZ", kind: Kind::Enum },
    // enum FactionType
    Probe { label: "Character::GetOriginalFaction", symbol: "?GetOriginalFaction@Character@GAME@@UEBA?AW4FactionType@2@XZ", kind: Kind::Enum },
    // bool
    Probe { label: "Character::GetOverKilled", symbol: "?GetOverKilled@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::GetShouldRenderAcrossPortals", symbol: "?GetShouldRenderAcrossPortals@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::GetShowAngerLevels", symbol: "?GetShowAngerLevels@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::GetSpawnAnimationEnabled", symbol: "?GetSpawnAnimationEnabled@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // enum FactionType
    Probe { label: "Character::GetVisibleFaction", symbol: "?GetVisibleFaction@Character@GAME@@QEBA?AW4FactionType@2@XZ", kind: Kind::Enum },
    // enum AnimationSet_Type
    Probe { label: "Character::GetWalkAnimationType", symbol: "?GetWalkAnimationType@Character@GAME@@QEBA?AW4AnimationSet_Type@2@XZ", kind: Kind::Enum },
    // bool
    Probe { label: "Character::GiveExperience", symbol: "?GiveExperience@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::HasModifierPointsInUse", symbol: "?HasModifierPointsInUse@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IgnoreDissolveDelay", symbol: "?IgnoreDissolveDelay@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IgnoreWhenPathing", symbol: "?IgnoreWhenPathing@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::InChallengeArea", symbol: "?InChallengeArea@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::InEndlessDungeon", symbol: "?InEndlessDungeon@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsAlive", symbol: "?IsAlive@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsAttackMoving", symbol: "?IsAttackMoving@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsControllingCharacter", symbol: "?IsControllingCharacter@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsEvading", symbol: "?IsEvading@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsFrozenOrPetrified", symbol: "?IsFrozenOrPetrified@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsGod", symbol: "?IsGod@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsHiding", symbol: "?IsHiding@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsImmobilized", symbol: "?IsImmobilized@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsInvincible", symbol: "?IsInvincible@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsInvincibleInDbr", symbol: "?IsInvincibleInDbr@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsJumping", symbol: "?IsJumping@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsKnockedDown", symbol: "?IsKnockedDown@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsMaxLevel", symbol: "?IsMaxLevel@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsMenuCharacter", symbol: "?IsMenuCharacter@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsMovementDisabled", symbol: "?IsMovementDisabled@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsMoving", symbol: "?IsMoving@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsOfInterest", symbol: "?IsOfInterest@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsOmnipotent", symbol: "?IsOmnipotent@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsPathing", symbol: "?IsPathing@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsQuestPet", symbol: "?IsQuestPet@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsRegisteredForForcedUpdates", symbol: "?IsRegisteredForForcedUpdates@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsTargetable", symbol: "?IsTargetable@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsTargetableInDbr", symbol: "?IsTargetableInDbr@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::IsTeleporting", symbol: "?IsTeleporting@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::JustSpawnedWithAnimation", symbol: "?JustSpawnedWithAnimation@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::OccludesPathing", symbol: "?OccludesPathing@Character@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::ShouldDoLateCrumple", symbol: "?ShouldDoLateCrumple@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::ShouldDoRagDoll", symbol: "?ShouldDoRagDoll@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::ShouldLoadLoot", symbol: "?ShouldLoadLoot@Character@GAME@@MEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::ShouldRotateWhenChatting", symbol: "?ShouldRotateWhenChatting@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::ShouldSuppressDeathSpawner", symbol: "?ShouldSuppressDeathSpawner@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::ShouldSuppressDyingSkill", symbol: "?ShouldSuppressDyingSkill@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::ShouldSuppressLoot", symbol: "?ShouldSuppressLoot@Character@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Character::ShouldUseDistressCall", symbol: "?ShouldUseDistressCall@Character@GAME@@MEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::AllocateAllAnimSets", symbol: "?AllocateAllAnimSets@Player@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::DeleteOnEnteringUnloadedLevel", symbol: "?DeleteOnEnteringUnloadedLevel@Player@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::DoDebugRender", symbol: "?DoDebugRender@Player@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::GetAlternateConfig", symbol: "?GetAlternateConfig@Player@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::GetAlternateConfigEnabled", symbol: "?GetAlternateConfigEnabled@Player@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // enum GameDifficulty
    Probe { label: "Player::GetGreatestDifficultyCompleted", symbol: "?GetGreatestDifficultyCompleted@Player@GAME@@QEBA?AW4GameDifficulty@2@XZ", kind: Kind::Enum },
    // enum GameDifficulty
    Probe { label: "Player::GetGreatestSurvivalDifficultyCompleted", symbol: "?GetGreatestSurvivalDifficultyCompleted@Player@GAME@@QEBA?AW4GameDifficulty@2@XZ", kind: Kind::Enum },
    // bool
    Probe { label: "Player::GetHasBeenInGame", symbol: "?GetHasBeenInGame@Player@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::GetIsBackup", symbol: "?GetIsBackup@Player@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // enum GameDifficulty
    Probe { label: "Player::GetLastDifficultyPlayed", symbol: "?GetLastDifficultyPlayed@Player@GAME@@QEBA?AW4GameDifficulty@2@XZ", kind: Kind::Enum },
    // enum PlayerCharacterClassType
    Probe { label: "Player::GetPlayerCharacterClass", symbol: "?GetPlayerCharacterClass@Player@GAME@@QEBA?AW4PlayerCharacterClassType@2@XZ", kind: Kind::Enum },
    // bool
    Probe { label: "Player::IsAlive", symbol: "?IsAlive@Player@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::IsCopy", symbol: "?IsCopy@Player@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::IsHardcore", symbol: "?IsHardcore@Player@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::IsInMainQuest", symbol: "?IsInMainQuest@Player@GAME@@QEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::IsInvincible", symbol: "?IsInvincible@Player@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::IsPlayer", symbol: "?IsPlayer@Player@GAME@@UEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::ShouldLoadLoot", symbol: "?ShouldLoadLoot@Player@GAME@@MEBA_NXZ", kind: Kind::Bool },
    // bool
    Probe { label: "Player::ShouldUseDistressCall", symbol: "?ShouldUseDistressCall@Player@GAME@@MEBA_NXZ", kind: Kind::Bool },
];
