"""Generate crates/grimlua-core/src/probe_table.rs from the symbol index.

Selects every zero-argument, non-static, `const` member of GameEngine that
returns a bool or an enum. Those are safe to call speculatively: they take no
arguments to get wrong and, being const, cannot mutate game state. Probing
them while a human opens and closes UI panels is how we find named state
without a disassembler.

    python tools/gen_probes.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
INDEX = ROOT / "symbols" / "symbols.json"
OUT = ROOT / "crates" / "grimlua-core" / "src" / "probe_table.rs"

# (rust table name, classes, what the `this` pointer is)
GROUPS = [
    ("PROBES_ENGINE", ["GameEngine"], "GameEngine*"),
    ("PROBES_CHARACTER", ["Player", "Character"], "Player* (usable as Character*)"),
]


def collect(data, classes):
    picks = []
    for s in data["symbols"]:
        if s["cls"] not in classes or not s["is_function"]:
            continue
        if s["is_static"] or not s["is_const"] or s["params"]:
            continue
        ret = s["return_type"]
        if ret.endswith("bool"):
            kind = "Bool"
        elif "enum" in ret and "*" not in ret and "&" not in ret:
            kind = "Enum"
        else:
            continue
        picks.append((s["cls"], s["method"], s["mangled"], kind, ret.replace("GAME::", "")))
    picks.sort(key=lambda p: (p[0], p[1]))
    return picks


def main() -> None:
    data = json.loads(INDEX.read_text(encoding="utf-8"))

    lines = [
        "//! Generated by tools/gen_probes.py -- do not edit by hand.",
        "//!",
        "//! Every zero-argument `const` member of the listed classes returning a",
        "//! bool or an enum. They take no arguments to get wrong and cannot mutate",
        "//! game state, which makes them safe to call speculatively from the frame",
        "//! hook while a human opens and closes UI panels.",
        "//!",
        "//! Caveat: a `virtual` getter is called here through its base-class",
        "//! implementation, bypassing dispatch. Fine for discovery, not for use.",
        "",
        "use super::probe::{Kind, Probe};",
        "",
    ]
    total = 0
    for table, classes, this_is in GROUPS:
        picks = collect(data, classes)
        total += len(picks)
        lines.append(f"/// Called with `this` = {this_is}.")
        lines.append(f"pub const {table}: &[Probe] = &[")
        for cls, method, mangled, kind, ret in picks:
            lines.append(f'    // {ret}')
            lines.append(
                f'    Probe {{ label: "{cls}::{method}", '
                f'symbol: "{mangled}", kind: Kind::{kind} }},'
            )
        lines += ["];", ""]

    OUT.write_text(chr(10).join(lines), encoding="utf-8")
    print(f"{total} probes -> {OUT}")


if __name__ == "__main__":
    main()
